apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prefix all names with "web-ui-".
namePrefix:
  web-ui-

# Use common BuildConfigs, ImageStreams, and Tekton resources.
bases:
  - ../../base/03-cicd/01-builds-images
  - ../../base/03-cicd/03-pipelines

# Common labels to add to all resources.
commonLabels:
  app: web-ui
  app.kubernetes.io/component: web-ui
  app.kubernetes.io/instance: web-ui

# Common annotations to add to all resources.
commonAnnotations:
  app.openshift.io/vcs-ref: main
  app.openshift.io/vcs-uri: https://github.com/pittar-gameoflife/web-ui

patchesJson6902:
  # Patch the BuildConfig to output to the correct ImageStream.
  - target:
      group: build.openshift.io
      version: v1
      kind: BuildConfig
      name: binary-build
    path: 01-buildconfig-patch.yaml
