apiVersion: v1
kind: Service
metadata:
  labels:
    app: decisions
    app.kubernetes.io/component: decisions
    app.kubernetes.io/instance: decisions
    app.kubernetes.io/part-of: gameoflife
    prometheus-metrics: 'true'
  name: decisions
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: decisions
    deploymentconfig: decisions
  sessionAffinity: None
  type: ClusterIP
