apiVersion: v1
kind: Service
metadata:
  labels:
    app: supervisor
    app.kubernetes.io/component: supervisor
    app.kubernetes.io/instance: supervisor
    app.kubernetes.io/part-of: gameoflife
    prometheus-metrics: 'true'
  name: supervisor
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: supervisor
    deploymentconfig: supervisor
  sessionAffinity: None
  type: ClusterIP
