kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: supervisor-initial-run
spec:
  pipelineRef:
    name: supervisor-build-and-rollout
  params:
    - name: "git-url"
      value: "https://github.com/pittar-gameoflife/supervisor.git"
    - name: "git-revision"
      value: "main"
    - name: "app-name"
      value: "supervisor"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: supervisor-workspace
    - name: maven-settings-cm
      configMap:
        name: maven-settings-cm