apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quarkus-metrics
spec:
  selector:
    matchLabels:
      prometheus-metrics: "true"
  endpoints:
  - port: 8080-tcp
    path: /q/metrics
    scheme: http